In [1]:
import numpy as np

In [2]:
arr = np.random.rand(5,5)
arr

array([[0.22910279, 0.34673557, 0.01944559, 0.10704303, 0.08431606],
       [0.74579569, 0.13690577, 0.13993884, 0.70771611, 0.27893311],
       [0.3119672 , 0.09589592, 0.27188242, 0.68133389, 0.30462531],
       [0.35523036, 0.32191795, 0.19829371, 0.0896173 , 0.95154404],
       [0.0428319 , 0.35352113, 0.01416589, 0.7208253 , 0.57047739]])

### element-wise addition, subtraction, multiplication and division

In [5]:
print(arr + 10)
print()
print(arr - 10)
print()
print(arr * 10)
print()
print(arr / 10)

[[10.99204921 10.33625988 10.76229726 10.30708472 10.28396832]
 [10.32325601 10.22808624 10.33798978 10.72966829 10.8433241 ]
 [10.65950852 10.46515341 10.97456116 10.73793109 10.53941794]
 [10.8731549  10.46222255 10.82816284 10.34286939 10.85861382]
 [10.10430531 10.46060853 10.06960882 10.1897318  10.31496808]]

[[-9.00795079 -9.66374012 -9.23770274 -9.69291528 -9.71603168]
 [-9.67674399 -9.77191376 -9.66201022 -9.27033171 -9.1566759 ]
 [-9.34049148 -9.53484659 -9.02543884 -9.26206891 -9.46058206]
 [-9.1268451  -9.53777745 -9.17183716 -9.65713061 -9.14138618]
 [-9.89569469 -9.53939147 -9.93039118 -9.8102682  -9.68503192]]

[[9.92049213 3.36259884 7.62297262 3.07084718 2.83968321]
 [3.23256011 2.28086238 3.37989779 7.29668285 8.43324097]
 [6.59508521 4.65153411 9.74561156 7.37931088 5.39417937]
 [8.73154903 4.62222547 8.28162841 3.42869393 8.58613821]
 [1.04305312 4.60608527 0.69608816 1.89731802 3.14968081]]

[[0.09920492 0.03362599 0.07622973 0.03070847 0.02839683]
 [0.0323256  0.0

In [6]:
# the above operations can be performed using numpy built-in functions
# which can save memory as the output can be stored in the original array rather than assigning new memory
arr1 = np.array([1,2,3])
x = np.add(arr1, [8,9,10], out=arr1)
print(arr1)

np.subtract(arr1, [2,1,12], out=arr1)
print(arr1)

np.multiply(arr1, [1,2,3], out=arr1)
print(arr1)

[ 9 11 13]
[ 7 10  1]
[ 7 20  3]


### element-wise exponentiation

In [7]:
print(np.exp(arr))

[[2.69675504 1.39970274 2.14319405 1.35945613 1.32839085]
 [1.38161902 1.25619365 1.40212617 2.07439239 2.32407962]
 [1.93384166 1.59225844 2.65000402 2.09160369 1.71500833]
 [2.39445322 1.58759858 2.28910942 1.40898473 2.3598872 ]
 [1.10993928 1.58503823 1.07208872 1.20892532 1.37021557]]


### element-wise logorithm

In [8]:
# natural log ( base e )
print(np.log(arr)) 

[[-0.00798256 -1.08987095 -0.27141869 -1.18063162 -1.25889259]
 [-1.12931067 -1.47803148 -1.08473962 -0.31516525 -0.17040394]
 [-0.41626039 -0.76538801 -0.02576801 -0.30390484 -0.61726462]
 [-0.1356423  -0.7717088  -0.18854548 -1.07040568 -0.15243603]
 [-2.26043299 -0.77520678 -2.66486406 -1.66214377 -1.15528398]]


In [9]:
# base 2
print(np.log2(arr))     

[[-0.0115164  -1.57235142 -0.3915744  -1.70329138 -1.8161981 ]
 [-1.6292509  -2.13234869 -1.56494848 -0.45468735 -0.24584092]
 [-0.6005368  -1.10422149 -0.03717537 -0.438442   -0.8905246 ]
 [-0.19569048 -1.11334046 -0.27201362 -1.54426897 -0.2199187 ]
 [-3.26111547 -1.11838698 -3.84458616 -2.39796658 -1.66672246]]


In [10]:
# base 10
print(np.log10(arr))    

[[-0.00346678 -0.47332494 -0.11787564 -0.5127418  -0.54673011]
 [-0.49045339 -0.64190092 -0.47109643 -0.13687453 -0.07400549]
 [-0.18077959 -0.33240379 -0.0111909  -0.13198419 -0.26807462]
 [-0.0589087  -0.33514887 -0.08188426 -0.46487128 -0.06620212]
 [-0.98169357 -0.33666803 -1.15733575 -0.72185987 -0.50173346]]


### element-wise square root

In [11]:
print(np.sqrt(arr))

[[0.99601667 0.5798792  0.87309636 0.55415225 0.53288678]
 [0.56855608 0.47758375 0.58136888 0.85420623 0.91832679]
 [0.8121013  0.68202156 0.98719864 0.85902915 0.73445077]
 [0.93442758 0.67986951 0.91003453 0.5855505  0.92661417]
 [0.32296333 0.67868146 0.26383483 0.43558214 0.56122017]]


### element-wise sine and cosine

In [12]:
print(np.sin(arr))

[[0.83714861 0.32995876 0.69058476 0.30228102 0.28016724]
 [0.31765561 0.22611374 0.33159127 0.66662241 0.74685771]
 [0.61272851 0.44855992 0.82745554 0.67275864 0.51363666]
 [0.7663595  0.44593853 0.73669027 0.33619085 0.75693744]
 [0.10411628 0.4444933  0.06955262 0.18859552 0.30978612]]


In [13]:
print(np.cos(arr))

[[0.54697551 0.94399535 0.72325147 0.95321885 0.95995121]
 [0.94820616 0.97410091 0.94342314 0.74539557 0.66498388]
 [0.79029347 0.89375276 0.56153123 0.73986202 0.8580078 ]
 [0.64241196 0.89506359 0.67623032 0.94179388 0.65348735]
 [0.99456513 0.89578218 0.99757828 0.98205485 0.95080627]]


### sum along a specified axis

In [14]:
# sum along the row
print(np.sum(arr, axis=0))    

[2.95227396 1.95233061 2.97261985 2.30728529 2.84029226]


In [15]:
# sum along the column
print(np.sum(arr, axis=1))    

[2.6816594  2.46232441 3.37657211 3.36502351 1.13922254]


In [16]:
print(np.sum(arr))

13.02480196454599


### compute the min and max along a specified axis

In [17]:
# calculate min along the row
print(np.min(arr, axis=0))

[0.10430531 0.22808624 0.06960882 0.1897318  0.28396832]


In [18]:
# calculate max along the column
print(np.max(arr, axis=1))    

[0.99204921 0.8433241  0.97456116 0.8731549  0.46060853]


In [19]:
# if axis not specified, calculate the max/min value of all elements
print(np.max(arr))
print(np.min(arr))

0.9920492134315917
0.06960881582035172


### compute the indices of the min and max along a specified axis

In [20]:
arr

array([[0.99204921, 0.33625988, 0.76229726, 0.30708472, 0.28396832],
       [0.32325601, 0.22808624, 0.33798978, 0.72966829, 0.8433241 ],
       [0.65950852, 0.46515341, 0.97456116, 0.73793109, 0.53941794],
       [0.8731549 , 0.46222255, 0.82816284, 0.34286939, 0.85861382],
       [0.10430531, 0.46060853, 0.06960882, 0.1897318 , 0.31496808]])

In [21]:
# along the row
print(np.argmin(arr, axis=0))
print()
print(np.argmax(arr, axis=0))

[4 1 4 4 0]

[0 2 2 2 3]


In [22]:
# along the column
print(np.argmin(arr, axis=1))
print(np.argmax(arr, axis=1))

[2 1 2 1 2]
[4 3 4 4 1]


In [22]:
# if axis not specified, return the index of the flattened array
print(np.argmin(arr))
print(np.argmax(arr))

19
18


In [21]:
arr

array([[0.26762104, 0.32633307, 0.38717747, 0.66373861, 0.37342205],
       [0.0612703 , 0.86632095, 0.66903482, 0.32633167, 0.21112867],
       [0.78140627, 0.64216104, 0.21016427, 0.014947  , 0.95493328],
       [0.44526838, 0.02785064, 0.50920261, 0.11466006, 0.89699822],
       [0.32762645, 0.09038554, 0.04149125, 0.58866664, 0.66182221]])

### compute element-wise min and max of two arrays

In [24]:
arr1 = np.array([1, 3, 5, 7, 9])
arr2 = np.array([0, 4, 3, 8, 7])
print(np.maximum(arr1, arr2))
print()
print(np.minimum(arr1, arr2))

[1 4 5 8 9]

[0 3 3 7 7]


### split fractional and integral parts of a floating-point array

In [26]:
print(20 / 3)
x = 20/3
x = str(x)
print(x.split("."))
anas = x.split(".")[1]
print(f"fraction = {anas}")
x = int(x[2:])

print(x)
print (20 // 3)

6.666666666666667
['6', '666666666666667']
fraction = 666666666666667
666666666666667
6


In [27]:
y= ((20/3)-(20 // 3))
print(y)
x = (len(str((20/3)-(20 // 3)))-2)
print(int((10**x) * y))

0.666666666666667
666666666666667


In [28]:
20 % 3

2

In [26]:
arr1 = np.random.rand(10) * 10

print(arr1)
print()
re, intg = np.modf(arr1)
print('fractional: ', re)
print('integral: ', intg)

[9.98334473 2.96717368 0.7977923  5.10874603 1.69011241 6.60565561
 7.45315441 3.87432335 4.86616336 5.83444669]

fractional:  [0.98334473 0.96717368 0.7977923  0.10874603 0.69011241 0.60565561
 0.45315441 0.87432335 0.86616336 0.83444669]
integral:  [9. 2. 0. 5. 1. 6. 7. 3. 4. 5.]


In [24]:
newarr = np.array([1.23,])
re , intg  = np.modf(newarr)

# rounding the number to get the accurate reuslt
fraction = round(float(re), 2)
integer = int(intg)
print(fraction)
print(integer)

0.23
1


### compute the mean

In [25]:
# compute the overall mean
print(np.mean(arr))

0.4609243847231879


In [26]:
# compute the mean along the row
print(np.mean(arr, axis=0))   

[0.38954095 0.33167975 0.41595967 0.70103912 0.46640243]


In [27]:
# compute the mean along the column
print(np.mean(arr, axis=1)) 

[0.36434456 0.37281029 0.51851523 0.42782468 0.62112715]


### compute the median

In [28]:
# compute the overall median
x = [1,2,4,6,7,8,9,12, 20]
print(np.median(x))

7.0


In [29]:
# compute the median along the row
print(np.median(arr, axis=0)) 

[0.30016114 0.335185   0.29645069 0.81802477 0.37011982]


In [30]:
# compute the median along the column
print(np.median(arr, axis=1))

[0.29645069 0.37233157 0.41089286 0.28236902 0.81802477]


### compute the percentile

In [26]:
arr1 = np.random.rand(100)
# compute 5, 65, and 95 percentiles of the array
print(np.percentile(arr1, [5, 65, 95]))

[0.06324113 0.68166079 0.98234324]


### compute the standard deviation & variance

In [27]:
# compute the overall standard deviation
print(np.std(arr))

0.31691421921254487


In [28]:
# compute the standard deviation along the row
print(np.std(arr, axis=0))

[0.40651498 0.22925625 0.24713125 0.37487395 0.16827072]


In [29]:
# compute the standard deviation along the column
print(np.std(arr, axis=1))

[0.24361673 0.31067439 0.19733453 0.36364029 0.34314561]


In [30]:
# compute the overall variance
print(np.var(arr))

0.10043462233909695


In [31]:
# compute the variance along the row
print(np.var(arr, axis=0))

[0.16525443 0.05255843 0.06107385 0.14053048 0.02831504]


In [32]:
# compute the variance along the column
print(np.var(arr, axis=1))

[0.05934911 0.09651858 0.03894092 0.13223426 0.11774891]


### compute the covariance & correlation

In [33]:
arr = np.random.rand(5,8)
arr

array([[0.04064895, 0.89118294, 0.29135691, 0.81655582, 0.26134072,
        0.36155554, 0.06299668, 0.758472  ],
       [0.49546723, 0.76564698, 0.53060514, 0.19441138, 0.41685174,
        0.60150772, 0.20362636, 0.44151339],
       [0.16392179, 0.59051272, 0.64007483, 0.2882677 , 0.31123202,
        0.30392522, 0.1715424 , 0.93755612],
       [0.30653595, 0.86487783, 0.09504024, 0.93590822, 0.64106486,
        0.81496541, 0.12099329, 0.49363603],
       [0.20349274, 0.6386304 , 0.22040807, 0.78094032, 0.95823322,
        0.63439705, 0.55598415, 0.18235264]])

In [36]:
print(np.cov(arr))

[[ 0.08567154 -0.02817149  0.00271483 -0.0123241  -0.00098763]
 [-0.02817149  0.0827715   0.0595721   0.03377884  0.02593071]
 [ 0.00271483  0.0595721   0.07330257  0.04615029  0.01890943]
 [-0.0123241   0.03377884  0.04615029  0.08110026  0.02107597]
 [-0.00098763  0.02593071  0.01890943  0.02107597  0.02630454]]


In [37]:
print(np.corrcoef(arr[:,0], arr[:,1]))

[[ 1.         -0.31083632]
 [-0.31083632  1.        ]]


### compute cumulative sum & product

In [39]:
       1 3 5 6 8 9
csum = 1 4 9 15 23 32
cpro = 1 3 15 90 720 ... 

SyntaxError: invalid syntax (<ipython-input-39-d4a9cd301553>, line 1)

In [38]:
# calculate the cumulative sums along the row
print(np.cumsum(arr, axis=0))    

[[0.07699789 0.52920376 0.7749342  0.88254456 0.67506679 0.57745162
  0.10032377 0.58024666]
 [0.59347426 0.78172712 1.45870061 0.94270848 1.43247299 0.75375814
  0.78049291 0.67714599]
 [1.09986086 1.17330089 2.3811652  1.39232364 2.00538267 0.95616065
  1.35953669 0.69077561]
 [1.4647305  1.86065436 3.28595412 1.49693147 2.157208   1.29359436
  1.92668225 0.86823552]
 [1.92426634 2.56012851 4.01952478 1.9937673  2.93777457 2.07162761
  2.74670332 1.28881656]]


In [39]:
# calculate the cumulative sums along the column
print(np.cumsum(arr, axis=1))    

[[0.07699789 0.60620165 1.38113585 2.26368041 2.9387472  3.51619882
  3.6165226  4.19676926]
 [0.51647637 0.76899973 1.45276614 1.51293005 2.27033626 2.44664277
  3.12681191 3.22371123]
 [0.50638659 0.89796037 1.82042495 2.27004012 2.84294979 3.04535231
  3.62439609 3.63802571]
 [0.36486965 1.05222312 1.95701205 2.06161987 2.2134452  2.55087891
  3.11802447 3.29548439]
 [0.45953584 1.15900999 1.89258064 2.38941647 3.16998304 3.94801629
  4.76803737 5.18861841]]


In [40]:
# calculate the cumulative product along the row
print(np.cumprod(arr, axis=0))   

[[7.69978878e-02 5.29203763e-01 7.74934202e-01 8.82544559e-01
  6.75066790e-01 5.77451620e-01 1.00323775e-01 5.80246662e-01]
 [3.97675900e-02 1.33636309e-01 5.29873976e-01 5.30973373e-02
  5.11299774e-01 1.01808483e-01 6.82371348e-02 5.62255095e-02]
 [2.01377744e-02 5.23284738e-02 4.88789978e-01 2.38733681e-02
  2.92928587e-01 2.06062932e-02 3.95122885e-02 7.66332348e-04]
 [7.34766265e-03 3.59681582e-02 4.42251759e-01 2.49734117e-03
  4.44739793e-02 6.95325795e-03 2.24092189e-02 1.35993275e-04]
 [3.37651432e-03 2.51587968e-02 3.24422912e-01 1.24076856e-03
  3.47149018e-02 5.40986586e-03 1.83760318e-02 5.71961928e-05]]


In [41]:
# calculate the cumulative product along the column
print(np.cumprod(arr, axis=1))  

[[7.69978878e-02 4.07475720e-02 3.15766872e-02 2.78678334e-02
  1.88126489e-02 1.08633946e-02 1.08985675e-03 6.32385739e-04]
 [5.16476375e-01 1.30422346e-01 8.91784193e-02 5.36532299e-03
  4.06372891e-03 7.16461884e-04 4.87315259e-04 4.72205193e-05]
 [5.06386594e-01 1.98287709e-01 1.82913390e-01 8.22406342e-02
  4.71164550e-02 9.53648907e-03 5.52204469e-03 7.52633727e-05]
 [3.64869647e-01 2.50794419e-01 2.26916013e-01 2.37371911e-02
  3.60390686e-03 1.21607966e-03 6.89694176e-04 1.22393071e-04]
 [4.59535838e-01 3.21433439e-01 2.35794138e-01 1.17150975e-01
  9.14441359e-02 7.11465780e-02 5.83416937e-02 2.45374102e-02]]


### element-wise comparison

In [42]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([5,4,3,2,1])

In [43]:
# return an array of bools
print(arr1 == arr2)    
print(arr1 < 3)

[False False  True False False]
[ True  True False False False]
